### ISSUE TITLE
Boltzman Constant

### ISSUE THREAD

**Issue by ghost** [callumjd/AMBER-Umbrella_COM_restraint_tutorial#2]
Hello!
Shall I know what's the value of Boltzmann constant (Kb and temperature) in your simulation for calculating permeability?

**Comment by callumjd** [comment]
The simulations were done at 303K using a restraint force constant of 2.5 kcal/mol. Is that what you are asking?

**Comment by ghost** [comment]
No, I mean the Boltzman constant in the permeability calculation equation.
When you want to calculate permeability or resistance for a bin, by having free energy and diffusion, what did you put for Kb? (You said T was 303 so for Beta I need to have Kb)

**Comment by callumjd** [comment]
I see what you are asking - the permeability calculation is done in windows/wham_run/overall_perm/parse_fe_diff.py . Everything is done in kcal / mol, so RT = 0.0019858775 * 303

**Comment by ghost** [comment]
Thanks for your information. 
I have a question regarding force constant. In your JACS paper, you used 1.1 kcal/mol force constant to pull the drug in your pulling simulation while you set force constant 2.5 kcal/mol for your production run. Why you used a different force constant? In principle, how you find out 1.1 and 2.5 are the right force constants for your pulling and MD production simulations?
I see some people set this value to 1000 Kj/mol for ligand pulling in the membrane which is a very different number.

**Comment by callumjd** [comment]
The pulling force constant is similar to Filipe et al: http://pubs.acs.org/doi/abs/10.1021/jp501622d

The windows force constant is similar to Carpenter et al: http://dx.doi.org/10.1016/j.bpj.2014.06.024

With the pulling, you want to cover the reaction coordinate while perturbing the membrane as little as possible. For the windows, we want to keep the molecule near the z-position it is restrained to while also having enough overlap with adjacent windows.

**Comment by ghost** [comment]
Thank you for your answer.
Let me ask one more question regarding pulling. May I know why you set the pulling rate 1 A/ns? How much the PMF curve and diffusion profile could be affected if you set it to 10 A/s?

**Comment by callumjd** [comment]
I don't recall exactly the reference for the pulling rate. Again, you want to cover the reaction coordinate while perturbing the membrane as little as possible.

It is double the pulling rate as Filipe et al: http://pubs.acs.org/doi/abs/10.1021/jp501622d

**Comment by ghost** [comment]
Actually, they used a 0.005 nm/ps pulling rate which this number is 0.1 nm/ps in your JACS paper and your pulling rate is 50 times slower! My question, in particular, is that why do you need to pull the drug that much slower?

**Comment by callumjd** [comment]
Right, it is a slow conservative pulling rate. The pulling is just to generate starting conformations for the window runs, which involve equilibration step. It still comes back to "With the pulling, you want to cover the reaction coordinate while perturbing the membrane as little as possible."

You can use a faster pulling rate as long as the conformations you obtain are suitable to start the PMF windows.
