### ISSUE TITLE
About the role of vector

### ISSUE THREAD

**Issue by hhhnano** [callumjd/AMBER-Umbrella_COM_restraint_tutorial#4]
The tutorial is very  useful for studying umbrella sample by Amber, I am very interested in it, I want to know what' the role for the command of " vector c0 :1 :1 out c0.out", Is it the center coordination of MOH or something else?
Thank you!

trajin ../pulling/md_output/05_Pull_DMPC_MOH_reduce.nc
center mass origin :2-217@N31
image center origin familiar
vector c0 :1 :1 out c0.out
trajout bilayer_zero.nc netcdf

**Comment by callumjd** [comment]
You can find out more about cpptraj in the Amber manual. But you are correct, this command asks cpptraj to calculate the position of the center of mass of residue 1, which is MOH.
