### ISSUE TITLE
com_placement.py

### ISSUE THREAD

**Issue by khelmy55** [callumjd/AMBER-Umbrella_COM_restraint_tutorial#5]
Hello,

I am trying to reproduce that tutorial on 3 ligands. Digoxin is the first on the list. I am kind of stuck at the placement in the center step. whenever I issue this command:

`/com_placement.py -i DMPC_72_relax.pdb -d digoxin.pdb -z 0 > dig_center.pdb`

I get the following error:

```
line 185, in <module>
    print("%s   %7.3 %7.3 %7.3" % (line[0:28],float(line[30:38])+move.x,float(line[38:46])+move.y,float(line[46:54])+move.z))
ValueError: could not convert string to float: 'ated by '
```

Alternatively, I built a membrane system myself in CHARMM GUI, and converted  the generated pdb file to amber lipid21, and re-ran the following:

`./com_placement.py -i step5_assembly.pdb -d digoxin.pdb -z 0 > dig_center.pdb`

and I got a dig_center.pdb file containing one line saying: 

Error: Cannot set bilayer center-of-mass

I believe my ligand has no unusual atom types/names

any idea what needs to be modified in the script?

**Comment by callumjd** [comment]
Hi, it looks as though you may have lines in digoxin.pdb that cannot be read by the script - if you delete all lines that do not start with ATOM or HETATM, does your first command work?

BTW digoxin is a large molecule with many rings. I would recommend to start the drug in the water layer (eg z=32) and drag it into the bilayer (reverse the pulling step compared to the tutorial). In the tutorial, methanol is a very small molecule so there is no issue to insert this in the bilayer middle. I would be worried that with digoxin, you will end up with may lipid tails overlapping with digoxin rings if you insert in the bilayer core.

**Comment by khelmy55** [comment]
thanks for your reply.
in the Digoxin.pdb, the records are HETATM and CONECT, I deleted the CONECT records, and still the issue remains.
neither DMPC_72_relax.pdb nor the DOPC I generated by CHARMM GUI and further parameterized it with Amber lipid21 works if specified as an input in the first command. Thank you for the tip, but do you mean that I shall change z to 32 instead of 0 in the script or, just leave out the centering step?

**Comment by callumjd** [comment]
The script is fairly simple, it seems it still cannot parse the PDB files.
If you are happy to share your input PDBs, attach them in the comment and I can take a look.
Yes I do mean insert the drug at z=32 (ie, the water layer) and then you will have to modify the md input file for the pulling step (just pull from z=32 to z=0 rather than z=0->32).

**Comment by khelmy55** [comment]
[files_for_placement.tar.gz](https://github.com/callumjd/AMBER-Umbrella_COM_restraint_tutorial/files/9240023/files_for_placement.tar.gz)

please find the files used in the placement step

**Comment by callumjd** [comment]
Hi, I have just updated the com_placement.py script - please download again and give it a try now:

python com_placement.py -i DMPC_72_relax.pdb -d digoxin.pdb -z 32

The error was due to the "REMARK  This PDB file was created by CS Chem3D." line in the digoxin.pdb file

**Comment by khelmy55** [comment]
thank you. 
that worked!
